"""Canon report generated by Gemini with Google Search grounding.

## The grounding tool shape, verified rather than assumed

The model id already surprised this project once — `gemini-2.5-flash` answers 404
"no longer available to new users" — so the tool field was probed against the
live API before being written here:

- `{"definitely_not_a_tool": {}}` → **400** `Unknown name ... Cannot find field`
- `{"google_search": {}}`, `{"googleSearch": {}}`, `{"google_search_retrieval": {}}`
  → **429** `RESOURCE_EXHAUSTED`

Field validation therefore runs *before* quota, which makes the 429 proof that
those three names are real fields. `google_search` is the snake_case spelling of
the current field and is what this module sends.

## Why degradation exists, and why it is loud

The same probe showed Search grounding returning 429 while plain generation
returned 200 in the same second. That is an entitlement (grounding needs a paid
tier), not a rate limit to wait out. So a grounded run on the current key will
fail every time, and the sane behaviour is to produce the report from measured
and reported evidence instead of nothing.

But the degraded report must never imply a verification that did not happen:
the generator name says `ungrounded`, and every `cited` claim is discarded —
without grounding, a "citation" from the model is a claim nobody checked.
"""

from __future__ import annotations

import json
from typing import Any

import httpx

from app.services.canon import CANON_POINTS
from app.services.canon_report import CanonReport, build_canon_report
from app.services.report import SiteSignals
from app.services.report_gemini import (
    _FENCE,
    API_BASE,
    DEFAULT_GEMINI_MODEL,
    REQUEST_TIMEOUT_SECONDS,
    ModelResponseInvalid,
    ModelUnavailable,
)

#: Verified against the live API — see the module docstring.
GROUNDING_TOOL: dict[str, dict] = {"google_search": {}}


class GroundingUnavailable(Exception):
    """Search grounding was refused and degradation is switched off."""


def _system_instruction(locale: str) -> str:
    language = "Spanish" if locale == "es" else "English"
    point_list = "\n".join(
        f"- {point.id}: {point.title} — {point.signal}" for point in CANON_POINTS
    )

    return (
        "You verify facts about a prospective client's software delivery workflow and "
        f"return evidence, not prose. Write any human-readable text in {language}.\n"
        "You receive VALIDATED FACTS about the company. Use Google Search to check public "
        "claims about them (stack, team, engineering practices).\n\n"
        "The ten canon points you may report on, by id:\n"
        f"{point_list}\n\n"
        "Rules you must follow:\n"
        "- Return ONLY claims you can attribute. Every claim needs a source.\n"
        "- source is `reported` when the company itself stated it in the facts given, or "
        "`cited` when you found it online. Never invent a third value.\n"
        "- A `cited` claim MUST carry `ref`: the URL you found it at. No URL, no claim.\n"
        "- Set `contradicts_reported: true` on a cited claim that disagrees with what the "
        "company reported. Do not resolve the disagreement yourself.\n"
        "- Set `partial: true` when the practice exists but without a gate enforcing it.\n"
        "- If you find nothing about a point, omit it. An omission is a valid answer and is "
        "better than a guess.\n"
        "- Never state that the company lacks a practice. Absence of evidence is not "
        "evidence of absence, and the report handles that itself.\n\n"
        "Answer with a single JSON object: {\"claims\": [...]}. Each claim is an object with "
        "`point_id` (one of the ids above), `text`, `source`, and optionally `ref`, "
        "`partial` and `contradicts_reported`. Return an empty list if you found nothing."
    )


#: A flat list, not a map keyed by point id. Dynamic keys cannot be expressed as a
#: responseSchema, and asking a thinking model for them produced
#: `MALFORMED_FUNCTION_CALL` with an empty answer against the live API.
_RESPONSE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "claims": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "point_id": {"type": "string"},
                    "text": {"type": "string"},
                    "source": {"type": "string", "enum": ["reported", "cited"]},
                    "ref": {"type": "string"},
                    "partial": {"type": "boolean"},
                    "contradicts_reported": {"type": "boolean"},
                },
                "required": ["point_id", "text", "source"],
            },
        }
    },
    "required": ["claims"],
}

_POINT_IDS = {point.id for point in CANON_POINTS}


def group_claims(document: dict) -> tuple[dict[str, list], dict[str, list]]:
    """Split a flat claim list into (reported, cited), keyed by canon point id.

    Claims naming a point that does not exist are dropped: an invented point id
    is the same class of error as an unsourced claim.
    """
    reported: dict[str, list] = {}
    cited: dict[str, list] = {}

    claims = document.get("claims")
    if not isinstance(claims, list):
        return reported, cited

    for claim in claims:
        if not isinstance(claim, dict):
            continue

        point_id = claim.get("point_id")
        if point_id not in _POINT_IDS:
            continue

        bucket = cited if claim.get("source") == "cited" else reported
        bucket.setdefault(point_id, []).append(claim)

    return reported, cited


def _facts_payload(
    *, contact_name: str, company: str, team: str | None, site: SiteSignals
) -> dict[str, Any]:
    """What the model is allowed to see. No email, no transcript, no free text."""
    return {
        "contact_name": contact_name,
        "company": company,
        "team": team,
        "site": site.model_dump(exclude_none=True),
    }


class GroundedCanonGenerator:
    """Generates a canon report, verifying claims with Search when entitled."""

    def __init__(
        self,
        *,
        api_key: str,
        model: str = "",
        transport: httpx.AsyncBaseTransport | None = None,
        degrade_without_grounding: bool = True,
    ) -> None:
        self._api_key = api_key
        self._model = (model or DEFAULT_GEMINI_MODEL).strip()
        self._transport = transport
        self._degrade = degrade_without_grounding

    @property
    def endpoint(self) -> str:
        return f"{API_BASE}/{self._model}:generateContent"

    async def generate(
        self,
        *,
        contact_name: str,
        company: str,
        locale: str = "es",
        team: str | None = None,
        site: SiteSignals,
        transcript: str | None = None,  # noqa: ARG002 — accepted and deliberately ignored
    ) -> CanonReport:
        """Generate the report.

        `transcript` is accepted so callers holding one cannot accidentally pass
        it somewhere it *would* be sent: this signature swallows it. The
        generation stage sees validated facts only (ADR 0007), and a test asserts
        the transcript never appears in a request body.
        """
        facts = _facts_payload(contact_name=contact_name, company=company, team=team, site=site)

        grounded = True
        try:
            document = await self._call(facts=facts, locale=locale, grounded=True)
        except GroundingUnavailable:
            if not self._degrade:
                raise
            grounded = False
            document = await self._call(facts=facts, locale=locale, grounded=False)

        reported, cited = group_claims(document)

        return build_canon_report(
            contact_name=contact_name,
            company=company,
            locale=locale,
            team=team,
            site=site,
            reported=reported,
            # Without grounding there is nothing to cite: keeping the model's
            # "citations" would keep claims nobody verified.
            cited=cited if grounded else {},
            generator=(
                f"gemini:{self._model}:grounded"
                if grounded
                else f"gemini:{self._model}:ungrounded"
            ),
        )

    async def _call(self, *, facts: dict, locale: str, grounded: bool) -> dict:
        payload: dict[str, Any] = {
            "systemInstruction": {"parts": [{"text": _system_instruction(locale)}]},
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": "VALIDATED FACTS:\n" + json.dumps(facts, indent=2)}],
                }
            ],
            "generationConfig": {"temperature": 0},
        }

        if grounded:
            payload["tools"] = [GROUNDING_TOOL]
        else:
            # Neither responseMimeType nor responseSchema can be combined with
            # tools on this API, so schema-enforced JSON is only available on the
            # ungrounded call. The grounded call relies on the prompt.
            payload["generationConfig"]["responseMimeType"] = "application/json"
            payload["generationConfig"]["responseSchema"] = _RESPONSE_SCHEMA

        try:
            async with httpx.AsyncClient(
                transport=self._transport, timeout=REQUEST_TIMEOUT_SECONDS
            ) as client:
                response = await client.post(
                    self.endpoint,
                    json=payload,
                    headers={"x-goog-api-key": self._api_key},
                )
        except httpx.HTTPError as error:
            raise ModelUnavailable(f"model transport failed ({type(error).__name__})") from error

        if response.status_code == 429 and grounded:
            # Entitlement, not load: the caller decides whether to degrade.
            raise GroundingUnavailable("search grounding is not available for this key")

        if response.is_error:
            raise ModelUnavailable(f"model refused the request with {response.status_code}")

        return self._parse(response)

    @staticmethod
    def _parse(response: httpx.Response) -> dict:
        try:
            body = response.json()
            candidate = body["candidates"][0]
            parts = candidate["content"]["parts"]
        except (ValueError, KeyError, IndexError, TypeError) as error:
            raise ModelResponseInvalid("model response had no usable candidate") from error

        # A thinking model can answer 200 with an empty text part and a non-STOP
        # finishReason — MALFORMED_FUNCTION_CALL is what the live API returned
        # here. Reporting that as "did not answer with JSON" sends an operator
        # hunting for a parsing bug that does not exist, so name the reason.
        text = "".join(part.get("text") or "" for part in parts if isinstance(part, dict))
        reason = candidate.get("finishReason") or ""

        if not text.strip():
            raise ModelResponseInvalid(
                f"model returned no text (finishReason: {reason or 'unspecified'})"
            )

        if reason and reason not in {"STOP", "MAX_TOKENS"}:
            raise ModelResponseInvalid(f"model stopped early (finishReason: {reason})")

        try:
            document = json.loads(_FENCE.sub("", text))
        except ValueError as error:
            detail = f" (finishReason: {reason})" if reason else ""
            raise ModelResponseInvalid(f"model did not answer with JSON{detail}") from error

        if not isinstance(document, dict):
            raise ModelResponseInvalid("model answered with JSON that is not an object")

        return document
